
name: Update WakaTime stats

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: "false"
          BLOCKS: "░▒▓█"            # bar style; try "0123456789" or "0o."
          TIME_RANGE: "last_7_days" # or last_30_days
          LANG_COUNT: "5"
          SHOW_TIME: "true"
          SHOW_TOTAL: "false"
          STOP_AT_OTHER: "true"
```
